### ISSUE TITLE
read pdf show  error uncompress.py:72 Error -3 while decompressing: incorrect header check (364, 0)

### ISSUE THREAD

**Issue by allenkallz** [pmaupin/pdfrw#104]
While try to read pdf info in python console it shows following error

    >>> print PdfReader('Downloads/c.pdf').info
   [ERROR] uncompress.py:72 Error -3 while decompressing: incorrect header check (364, 0)
   [ERROR] uncompress.py:72 Error -3 while decompressing: incorrect header check (365, 0)
   [ERROR] uncompress.py:72 Error -3 while decompressing: incorrect header check (366, 0)
   [WARNING] tokens.py:228 Did not find PDF object (277, 0) (line=15000, col=1, token='endobj')
   [ERROR] pdfreader.py:472 Invalid page tree: 'NoneType' object has no attribute '__getitem__'
   None

I also attach the file which I am trying to read

[c.pdf](https://github.com/pmaupin/pdfrw/files/1241307/c.pdf)

**Comment by allenkallz** [comment]
@EdwardBetts @ndevenish please check and help me ?? waiting for response

**Comment by allenkallz** [comment]
@pmaupin please check and help me ?? still waiting for response

**Comment by JorjMcKie** [comment]
I don't know what exactly you are trying to achieve - and I am also not a pdfrw expert.
But what I see when inspecting the details of your file is, that it is not encrypted but password protected against changes and applying annotations. This is probably the stumble stone for pdfrw.
You can wash these properties away with several tools, e.g. `mutool clean -ggggz c.pdf c1.pdf` (MuPDF tool). This will yield `c1.pdf` without any protection (and also 50% smaller). There also is a Python binding for MuPDF, [PyMuPDF,](https://github.com/rk700/PyMuPDF) so that you can achieve these results seamlessly in Python.

**Comment by pmaupin** [comment]
Jorj is correct; pdfrw does not handle password protection.

**Comment by allenkallz** [comment]
@pmaupin @JorjMcKie I try to read only info of password protected file like total page, size etc when I create a manual password protected pdf I can read info but for this file, I am getting error.
