### ISSUE TITLE
pdfrw misbehaves when stream of a PdfDict is of type bytes()

### ISSUE THREAD

**Issue by johndoe31415** [pmaupin/pdfrw#161]
pdfrw writes the str() result of a bytes object that is given as a stream, instead of the raw bytes data. When trying to include raw binary data, this is not at all what we want, since it corrupts the data stream. Minimal example:

```
import pdfrw

pw = pdfrw.PdfWriter("test.pdf")
x = pdfrw.PdfDict()
x.stream = b"foobar"
pw.addpage(pdfrw.PdfDict({
	pdfrw.PdfName.Type:		pdfrw.PdfName.Page,
	pdfrw.PdfName.FooBar:	x,
}))
```

Results in:

```
<</Length 6>>
stream
b'foobar'
endstream
```

Expected would be:

```
<</Length 6>>
stream
foobar
endstream
```

Tested against pdfrw 0.4.

**Comment by pmaupin** [comment]
pdfrw works with both Python 2 and 3.

The Python core developers, in their infinite wisdom, borked bytes/string compatibility horribly, and intransigently made old-style ASCII strings ugly and difficult to work with in Python 3 by declaring a schism between bytes and strings that may have reflected web-realpolitik, but didn't at all reflect the real world that many developers live in. 

So all of pdfrw works on strings internally, because that was the path that required the fewest ugly changes to the bulk of the pdfrw code to make it work under Python 3.

This does mean that data into or out of pdfrw must be converted on Python 3.  To do this in a way that works under either Python 2 or 3, you can use `pdfrw.py23_diffs.convert_load()`:

```
>>> import pdfrw
>>> x = b"foobar"
>>> x
b'foobar'
>>> pdfrw.py23_diffs.convert_load(x)
'foobar'
```
