### ISSUE TITLE
Add tests to the release tarball

### ISSUE THREAD

**Issue by valholl** [pmaupin/pdfrw#29]
Could you please add the tests to your next release tarball? while the git repo is of course better for developement, having tests in the tarball is useful to check that the installation is working, expecially in the context of packaging (I'm in the process of adopting the packaging of pdfrw for debian).

Thanks in advance.

**Comment by pmaupin** [comment]
Thanks for your help on this!

I would love to work with you to figure out the best way to do this.  Unfortunately, 99% of the tests are functional, and I broke out the PDFs they use into the separate static_pdfs repository.  That's 24MB, and it's easy for me to believe you need those to test the packaging, but at the same time, that's a lot of cruft for a release tarball.

SO, what I did on this release:

- The release to PyPI doesn't even contain the tests (because they won't work without the PDFs).

- I clicked the button on github to make a corresponding release (tag v0.2).  Github puts all the files in the repository in that release, so it includes the tests, but not the data they need.

- If you extract the files from the github release, you will find there is a .travis.yml file, which describes how the automated tests are run, and has code to grab all the dependencies:

  - "git clone https://github.com/pmaupin/static_pdfs tests/static_pdfs"
install:
  - "pip install ."
  - "pip install reportlab || true"
  - "pip install zlib || true"
  - "pip install unittest2 || true"

Maybe the right answer is to start making releases for static_pdfs, and modify the code to grab one of those and test with it rather than to simply do a git clone?

In any case, if it would help, I can give you write access to the github repo as well, so you can play with things that would make your life easier.

Or maybe I'm just being old-fashioned and 24MB is no big deal.  Please let me know what you think.

Thanks,
Pat

**Comment by valholl** [comment]
Thanks for your quick reply.

I agree that adding 24MB that only a few people need to a <100k tarball is suboptimal (I may also be old-fashoned in this :) ); even worse however is the license status of the files: since they are not under a free license debian can't distribute them, and adding them even to the source package would be problematic.

Unluckily, even downloading the pdf files during the build is problematic: debian packages can't download anything from the internet during the build, to be sure that what is built correspond to the published sources (in this case there would be no risk, but this is a general rule).

Considering that right now having tests in the packages is a nice-to-have and not a requirement, I believe that the best thing to do right now would be to just skip tests in the package; I will probably add a note to the package explaining where to find the tests + pdf files if somebody wants to run them (and I will run them locally in a semimanual/ad-hoc script way while preparing the package for upload).

Sorry for opening the issue before I had fully investigated the situation.

**Comment by pmaupin** [comment]
> Sorry for opening the issue before I had fully investigated the situation.

No big deal at all -- I'm obviously intimately familiar with the situation, having created it...

Thanks again!
