### ISSUE TITLE
watermarking some PDFs doesn't work

### ISSUE THREAD

**Issue by ThomasWaldmann** [pmaupin/pdfrw#33]
I have some input PDFs and try to watermark them with a given single page watermark.pdf.
For some PDFs that works (watermark shows), for some not (output looks as input).

My code is like this, underneath=False:
https://github.com/pmaupin/pdfrw/blob/master/examples/watermark.py

Do you have an idea why? Is this a bug? How can it be debugged?

**Comment by pmaupin** [comment]
Can you provide example failing PDFs?

**Comment by ThomasWaldmann** [comment]
I first need to get some myself (which I may publish, with permission).

**Comment by pmaupin** [comment]
If they're not too sensitive, you could email them to me pmaupin -- gmail.

**Comment by ThomasWaldmann** [comment]
OK, thanks for the offer (and see your inbox).

**Comment by pmaupin** [comment]
The example you sent failed because the watermark page was taller than the pages in the document.

Since the origin inside PDF documents is at the lower-left corner, the text in the watermark was above the page (outside the cropping boundaries).

I have created pull request #34 with a [more comprehensive watermark example](https://github.com/pmaupin/pdfrw/blob/position_watermark/examples/fancy_watermark.py) that demonstrates how to move and scale the watermark to keep it on the page:



If this example meets your needs please let me know and I will merge it.

Thanks,
Pat

**Comment by ThomasWaldmann** [comment]
Oh, oops, that simple. I somehow assumed it to be a more complex problem (and I also assumed that my input PDFs are about A4 format).

Yes, the height of the problematic PDF was only 8.86". That and the origin of the coordinate system being bottom left explains why my rather huge testing watermark at the top (of A4, 11.69" height) "disappeared".

Thanks a lot for the fancy_watermark.py, I tried it and it works great!

**Comment by pmaupin** [comment]
Keeping open until I generate a test case for this and add it to the suite.

**Comment by qippur** [comment]
I am converting a text document to PDF, and I am using pdfrw to add a background image to each page, so I create each new page from scratch reading text and convert it to PDF pages.

Each document consists of several thousands pages.

To gain speed in document creation I want to do add the background to each page before adding it to the document.
The other constraint is the final document size: I want to set the mediabox at document level, and not for each page.

Unfortunately, doing so I get an AttributeError: 'NoneType' object has no attribute 'box'

To make it work, I have to:
- create basic objects (fonts, references, etc.)
- convert from text and add all the pages to the document
- set the mediabox for the document
- run the PagePerge for all the pages in the document

This slows down the process because each page is re-read from the document to add the background image. 

I am attaching a proof-of-concept program to better explain.

Thanks in advance for any help or suggestions.

--

[minimal.pdf](https://github.com/pmaupin/pdfrw/files/365771/minimal.pdf)

[unittest.py.txt](https://github.com/pmaupin/pdfrw/files/365766/unittest.py.txt)

**Comment by Chaoste** [comment]
I figured out a new problem. I cant provide my test files for everyone but the problem seems to be that the main pdf file consists is a scanned document (so its just one image). Executing your code therefore doesn't raise an error but the watermark is not visible. If I try it for another PDF which is generated from a word document (so it consists only of text elements) its working. You wanna have my test files, too? Or is there something I'm missing for this problem?

**Comment by qippur** [comment]
Likely the white parte of your scanned doc  is actually white and not
transparent. So it covers whatever background you put  under it.

Il 19/lug/2016 01:09, "Thomas Kellermeier" <notifications@github.com> ha
scritto:

**Comment by pmaupin** [comment]
If you send me the files, I will try to take a look at some point.

**Comment by pmaupin** [comment]
This only adds an example, which was tested by original user.  Will defer adding testcases until someone complains it doesn't work.
