### ISSUE TITLE
Stopiteration exception

### ISSUE THREAD

**Issue by tassamartz** [pmaupin/pdfrw#58]
Hello there,

First thanks for your great work!

I've been using this library for a while and it worked perfectly, my use case is the following:
 1- I build a pdf document with reportlab library
 2- I have other existing pdf documents that i append at the end of the document build in 1-. Till now every thing was fine till i encountered an error with a pdf file which when i want to add it at the end of the document, the program  exits with an error on Stopiteration exception. Following is the error stack. The pdf document in question is fine when opened with adobe  Acrobat reader and is made of 3 pages.  So is there something i can do to know that some pdf file are not supported ?

Thanks!

File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfwriter.py", line 316, in write
[Mon Jun 13 13:15:50.782466 2016] [:error] [pid 16822]     self.killobj, user_fmt=user_fmt)
[Mon Jun 13 13:15:50.782471 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfwriter.py", line 196, in FormatObjects
[Mon Jun 13 13:15:50.782476 2016] [:error] [pid 16822]     format_deferred()
[Mon Jun 13 13:15:50.782481 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfwriter.py", line 164, in format_deferred
[Mon Jun 13 13:15:50.782487 2016] [:error] [pid 16822]     objlist[index] = format_obj(obj)
[Mon Jun 13 13:15:50.782492 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfwriter.py", line 145, in format_obj
[Mon Jun 13 13:15:50.782512 2016] [:error] [pid 16822]     myarray.append(add(value))
[Mon Jun 13 13:15:50.782517 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfwriter.py", line 83, in add
[Mon Jun 13 13:15:50.782523 2016] [:error] [pid 16822]     result = format_obj(obj)
[Mon Jun 13 13:15:50.782528 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfwriter.py", line 135, in format_obj
[Mon Jun 13 13:15:50.782533 2016] [:error] [pid 16822]     myarray = [add(x) for x in obj]
[Mon Jun 13 13:15:50.782538 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/objects/pdfarray.py", line 46, in **iter**
[Mon Jun 13 13:15:50.782543 2016] [:error] [pid 16822]     self._resolve()
[Mon Jun 13 13:15:50.782548 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/objects/pdfarray.py", line 28, in _resolver
[Mon Jun 13 13:15:50.782554 2016] [:error] [pid 16822]     value = value.real_value()
[Mon Jun 13 13:15:50.782559 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/objects/pdfindirect.py", line 21, in real_value
[Mon Jun 13 13:15:50.782564 2016] [:error] [pid 16822]     value = self.value = self._loader(self)
[Mon Jun 13 13:15:50.782569 2016] [:error] [pid 16822]   File "/usr/local/lib/python2.7/dist-packages/pdfrw/pdfreader.py", line 200, in loadindirect
[Mon Jun 13 13:15:50.782574 2016] [:error] [pid 16822]     source.next()
[Mon Jun 13 13:15:50.782579 2016] [:error] [pid 16822] StopIteration

**Comment by takluyver** [comment]
Do you have a script and PDF you can share, either publicly or privately, that can reproduce this?

**Comment by pmaupin** [comment]
Publicly would be better; we could add it to the regression PDFs.

**Comment by divergentdave** [comment]
I have also hit StopIteration while parsing a PDF. The PDF is available at https://github.com/mozilla/pdf.js/raw/master/test/pdfs/close-path-bug.pdf, and the script and traceback are below. (This is using pdfrw 0.3)

```
>>> from pdfrw import PdfReader
>>> f = open("/home/david/pdf.js/test/pdfs/close-path-bug.pdf", "rb")
>>> doc = PdfReader(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.virtualenvs/pdf-redactor/lib/python3.4/site-packages/pdfrw/pdfreader.py", line 543, in __init__
    trailer, is_stream = self.parsexref(source)
  File "/home/david/.virtualenvs/pdf-redactor/lib/python3.4/site-packages/pdfrw/pdfreader.py", line 434, in parsexref
    tok = next()
```

These two files also produce StopIteration excpetions: https://bug867484.bugzilla.mozilla.org/attachment.cgi?id=744001 and http://web.archive.org/web/20150922201828/http://w2.eff.org/legal/cases/betamax/betamax_oral_argument2.pdf

**Comment by pmaupin** [comment]
Thank you for the test cases, @divergentdave.

They represent two different classes of errors.  close-path-bug.pdf and betamax_oral_argument2.pdf have invalid offsets for the xref tables, while the bugzilla issue PDF provokes an actual error in pdfrw parsing, with what (at first glance) appears to be a valid yet goofy stream object.

I have created a new branch that I believe fixes the bugzilla error, and gives a better exception for the other two files:

https://github.com/pmaupin/pdfrw/tree/fix_StopIteration

Please let me know what you think; in any case, I will leave the issue open until test cases can be added that show the bugs and then show them fixed.

Regards,
Pat

**Comment by divergentdave** [comment]
I can confirm that close-path-bug.pdf parses fine now, while the other two throw a PdfParseError. The changes look good to me! :clap:

**Comment by divergentdave** [comment]
Strike that, betamax_oral_argument2.pdf parses fine, while issue1536.pdf and close-path-bug.pdf throw PdfParseError.

**Comment by divergentdave** [comment]
Okay, I think I got my files straight this time. bug867484.pdf parses fine, so the fix worked there. The other two PDFs, issue1536.pdf, a.k.a. betamax_oral_argument2.pdf, and also close-path-bug.pdf, both raise a PdfParseError with the message `Expected "xref" keyword or xref stream object (filepos N past EOF M)`. Sorry for the confusion, and yes, the fix looks good on my end.

**Comment by tassamartz** [comment]
Hello there,

First thanks for your work and sorry I did not see the email notification in my box earlier!
Unfortunately, it's a customer document I can not share, however, I've run the new fix, and now I have the following error: tokens.py:236 stream /Length attribute (706238) appears to be too big (size 671132) -- adjusting (line=11870, col=1)

Hope this can help !

**Comment by pmaupin** [comment]
A StopIteration exception leaking from the bowels of pdfrw up into user code is an _a priori_ indication that there is a bug in pdfrw.

The error you are now seeing is not like that.  It is telling you that (a) pdfrw found what appears to it to be a broken PDF file (the reported length of a stream doesn't match the actual length of the stream), and (b) it tried to fix it by adjusting the reported length to the actual length it found.  The fact you're still not satisfied probably also means that (c) this fix was insufficient and there are other issues either with the PDF or with pdfrw.

Without seeing the PDF itself, I cannot know whether this is a bug in pdfrw or a problem with the PDF, but literally (no, not figuratively, literally) millions of PDFs have been run through pdfrw, and it's usually pretty good about diagnosing things, the original StopIteration bug notwithstanding.

In fact, some of the examples that other users sent me that caused StopIteration were, in fact bad PDFs, and the other users were quite sensibly happy to get decent reporting about the issues with the actual PDFs rather than the unhelpful StopIteration exception, and the example where StopIteration occurred on a valid PDF was on a corner case PDF that (IMHO) no sane PDF writer program would actually produce.

In any case, I couldn't have found either of those bugs _without looking at the PDFs_, so no PDF, no diagnostic work, and if I am asked to diagnose a PDFs that pdfrw gives a reasonable error message on (such as the one you describe), my first question will be how you know that it is, in fact, a valid PDF.  Because a lot of them aren't.

Note that, just because acrobat or okular or whatever accepts the PDF, that doesn't actually mean the PDF is valid, because all of those engines have exception code to try to clean up PDFs that are broken in common ways.

Personally, I'm rather ambivalent about Postel's law; if somebody submits reasonable looking code that fixes broken PDFs without slowing down or doing the wrong thing with correct PDFs, I'll accept it, but I don't have the time or inclination to go out of my way to try to fix a particular good PDF that I don't even have a copy of, and if the PDF isn't in fact a valid PDF, somebody else will have to submit a patch to cope with it.

Note that there are PDF repair tools out there that usually do a pretty good job, and in a production environment, you could shell out to one of them to create a fixed copy of the PDF if pdfrw reports an exception on the PDF.

Regards,
Pat

**Comment by pmaupin** [comment]
Still need to add tests.

**Comment by pmaupin** [comment]
If there was a label "fixed, awaiting tests" I'd apply it.  For now, going to close to stop looking at it.
