### ISSUE TITLE
Question: How to blacken text / Replace text / Remove text ?

### ISSUE THREAD

**Issue by AvnerCohen** [pmaupin/pdfrw#65]
Thanks for making this lib!
And sorry for the Question, this is not an issue.

I have an existing PDF with a specific word I want to hide out.
I am happy with any solution on how to hide it (Write on top of it, cut it out, replace it etc..).
I am not so much familier with the PDF format so not sure how to go about that, any suggestion?

Happy to contribute back a working example when I get this to work :)

**Comment by pmaupin** [comment]
pdfrw wasn't really designed for text extraction or manipulation.  If that's what you want, you might try pdfminer.

But...

If you really don't care whether a determined foe can reach into the PDF and figure out what the word is that you've redacted, and you know the coordinates and size of the word (or, to be more specific, you want to do this repeatedly at the same coordinates, so that it's worthwhile to figure those out), then pdfrw can certainly allow you to place a rectangle anywhere you want on a page.

If you look at the fancy_watermark examples, you will see how you can combine whole pages like this.  The pagemerge module that the example uses allows you to place one page (or a rectangle from a page) anywhere you want on top of another page.

If I were doing this, I would simply start by using something like inkscape to make a page (that could be any size, really) all one color.  But if you need white, make sure it's not transparent.   Then "watermark" your other page with that page, and play with the x/y coordinates of the watermark.

**Comment by pmaupin** [comment]
By the way, an example would certainly be appreciated.  Most of the examples aim to be fairly simple; to try to do one thing well, rather than do lots of things.

In addition to looking at the watermark examples, you might grep for pagemerge; a couple of the other examples use pagemerge with various coordinate manipulations.

**Comment by AvnerCohen** [comment]
@pmaupin Thanks so much for the quick response!
No, in my case I know only the actual text, it will appear in random places, with different fonts and size.
So I need something that is not based on some template logic.
As a last resort, I guess I can extract the text as text and manipulate that, but I want to try and stick to the original as much as possible.

I'll update if there is anything valuable I came up with related to pdfrw, closing for now.

**Comment by pmaupin** [comment]
There is some code in the examples/rl2 directory that is a starting point for decoding graphics and text commands.

Good luck!

**Comment by priyanshujain** [comment]
This tool worked for me https://github.com/JoshData/pdf-redactor
