### ISSUE TITLE
Inline images not handled

### ISSUE THREAD

**Issue by divergentdave** [pmaupin/pdfrw#67]
Inline images, as described at section 4.8.6 of the PDF 1.7 reference, turn content streams on their head by putting raw image data in the middle of normal PDF objects. It seems the tokenizer doesn't handle inline images at present, so the image data gets parsed into nonsense operators/operands. If there are left and right angle brackets in the image data, one of the tokens will be an invalid hex-encoded string, which will raise an assertion when you try to `decode()` it.

[I've started work on this in my fork](https://github.com/divergentdave/pdfrw/tree/inline-image), but I'm wondering if the image data should be returned as a different data type or object. I haven't looked at PdfWriter yet either.

I filed a PR over at pmaupin/static_pdfs#1 to add a file with inline images to the test files. If you run the script below on that file, you should get an AssertionError with a message of '<\x00\x00>'.

```
import sys

import pdfrw


with open(sys.argv[1], "rb") as f:
    doc = pdfrw.PdfReader(f)
    for page in doc.pages:
        if isinstance(page.Contents, pdfrw.PdfArray):
            contents = list(page.Contents)
        else:
            contents = [page.Contents]
        pdfrw.uncompress.uncompress(contents)
        for content in contents:
            if content is None:
                continue
            for token in pdfrw.PdfTokens(content.stream):
                if isinstance(token, pdfrw.PdfString):
                    token.decode()
```

**Comment by pmaupin** [comment]
The core of pdfrw uses the tokenizer quite heavily for parsing PDF objects, but never actually parses into content streams (although there is a simple example in rl2/examples that does use the tokenizer to parse into content streams, and I know of several users who have written their own similar content stream parsers on top of the tokenizer).  The tokenizer was designed to go fast and to be cheaply restartable when upper level code needs to parse into something special.

Essentially, if you are parsing the tokens in a content stream, when you encounter the BI token, you should read the tokenizer object's `floc` attribute to determine the location of the image data, extract the image data yourself and calculate its size, and then restart the tokenizer to the EI token by setting the `floc` attribute.    For an example of this, look for `floc` in pdfreader.py, especially readstream(), which has a very similar problem -- it finds the start and end of content streams.

Otherwise, if you modify the tokenizer as you propose, you'll be slowing down all PDF reading for all users, and that would make me sad.

Please take a look at pdfreader, and then let me know if this makes sense, or if you can articulate a reason why you really need to modify the tokenizer for this special case.

Thanks,
Pat

P.S. I'm not sure where pdfwriter figures into this -- when you hand it a content stream, it figures you know what you're doing, and outputs it.

P.P.S I also don't think that a grep for EI is going to give you long-term joy; there is no guarantee that some form of image data won't have that 16 bit pattern 'EI' embedded in it somewhere.  The right answer is to actually figure out how much space the image data occupies by using the data in the dictionary keys, and that could involve several different kinds of decompression (which are not yet supported by pdfrw core).

**Comment by divergentdave** [comment]
Okay, that makes sense, I think I can handle that in my application code.
