### ISSUE TITLE
Documents with a large number of Pages nodes cause RecursionError

### ISSUE THREAD

**Issue by troyhoffman** [pmaupin/pdfrw#92]
I'm not completely familiar with the PDF spec, so I apologize if my terminology is incorrect. 

If a PDF has a large number of /Type /Pages nodes, instantiating PdfReader causes a RecursionError: maximum recursion depth exceeded while calling a Python object in readpages().readnode()
 
The break point seems to be around 1954 nodes in the document, though that number varies depending on how nested the code is that creates the PdfReader object. This was found while attempting to split the pages from a document created by an application that uses WebSupergoo's ABCpdf.NET library (https://www.websupergoo.com/products.htm#abcpdf).  The pdfrw module is used as part of automation testing of this product. The initial file that triggered it was a real-world file, not a test file, so this will be encountered in the wild.
 
A solution might be to modify readpages().readnode() to not use recursion. One approach would be to use lists that track the Page objects found as well as the Pages/Catalogs objects that need to be processed. This solution is included in the attached file.
 
[pdfrw.zip](https://github.com/pmaupin/pdfrw/files/974324/pdfrw.zip) contains the following files:
- reecusion_test.py - The code from my automation that triggers this. Modify the source_file and output_directory variables as necessary.
- pdf_generator.py - A module that will let you generate simple PDF files with as many pages as you need. The destination_directory will need to be changed. It depends on reportlab.
- merger.cs - C# code that uses the ABCpdf.NET library to merge the files created by pdf_generator.py
- 977.pdf - This file reproduces the problem. It consists of 977 merged single page documents. It has been simplified as much as possible while still reproducing it.
- 976.pdf - This file does not reproduce the problem. It consists of 976 merged single page documents. It's essentially 977.pdf with one less document.
- 97600.pdf - This file contains 97,600 merged 100 page documents and does not reproduce the error. It may be useful for performance comparison.
- pdfreader.py - Contains a proposed fix.
 
The changes to pdfreader.py are:
- The __init__ takes a new parameter, use_readpages_new. If True, it uses the proposed fix. If False, it uses the original code (allowing for performance comparisons).
- A new method: use_readpages_new that contains a non-recursive readnode() function.

Note that I added the parameter and second method as a way to do comparisons between the proposed fix and the original method. If the fix is accepted, it could replace the existing method and the "use_readpages_new" parameter could be removed from __init__().
 
Testing performed on pdfreader.py:
- Ran all three PDFs through pdf_generator.py and compared performance of both methods. Memory usage and overall time was roughly identical. Due to time restraints, I didn't extract each page and only timed how long it took to parse the pages.
- Ran 976.pdf through pdf_generator.py with both methods and did a binary compare of the output files to ensure the extracted pages were correct. All files matched exactly, indicating that the pages not only were extracted properly, but that the order was correct.

**Comment by pmaupin** [comment]
First of all, thanks for the detailed report and the code.  It gets me thinking, because one of the approaches I have tried for the new writer uses iteration rather than recursion, and I haven't fully decided yet.  Your example shows there are some extant PDF files where recursion could fail.

But...

People have been using this library for several years and this is the first report of this, probably because it's a very inefficient, degenerate case to create a tree with one leaf node and one subtree per node.  If this code is faster or no slower than the original, it may be a no-brainer to use it.  But if it's significantly slower than the original, perhaps the right answer is to wrap execution of the original inside a `try / except RecursionError` block, and then execute this if that throws the exception.

Anyway, I'll try it on my regression and see what the times look like there.

Thanks,
Pat

**Comment by troyhoffman** [comment]
The sample files I included were greatly simplified to show the problem. The original file was created by merging about 1500 letters, each 29 pages, with ABCpdf.NET. It has the same basic structure, but more pages per node. The app that generates the PDF basically concatenates a bunch of smaller PDFs into one large PDF, resulting in a node per input file.

Unfortunately, I can't send the original file I found this with since it contains confidential data. However, I can try to put together sample files that are closer to the original for performance testing. In the meantime, I'll put together my own class to override the method so my automated testing can continue.

**Comment by pmaupin** [comment]
That makes more sense.  It's real-life in terms of a new scale not seen before rather than a denial-of-service attack by generating a bad PDF.  So, I'll look at merging your change unless there's a significant performance degradation (and I could even believe that if it's done properly, the performance is better because of the reduced calls).

Thanks,
Pat

**Comment by pmaupin** [comment]
The iterative version didn't take much more time, and after I re-wrote it to always muck around with the end of the list rather than the front, it was essentially identical timing to the original, so I merged it into master.

Bonus: exposed and fixed a bug where I didn't deal with `__reversed__` properly in `PdfArray`.

I'll leave it open until you've verified you're happy with it.

Thanks!
Pat

**Comment by troyhoffman** [comment]
I think I ran into that bug with __reversed__. I thought I was doing something wrong, which is why my code wound up converting to a list before reversing. 

As for the fix, it looks good. It's a little faster than mine and the page order is correct on the complex PDFs. As a plus, you can now handle PDFs that other libraries and utilities fail on, including GhostScript. I think it's ready to close.

**Comment by pmaupin** [comment]
Fixed with PR #93.
